const styles = {
    container: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      height: "100vh",
      backgroundColor: "#f4f4f4",
    },
    box: {
      backgroundColor: "white",
      padding: "40px",
      borderRadius: "10px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
      textAlign: "center",
      width: "350px",
      margin: "20px auto",
    },
    input: {
      width: "100%",
      padding: "12px",
      margin: "10px 0",
      border: "1px solid #ccc",
      borderRadius: "10px",
      boxSizing: "border-box",
    },
    
    button: {
      width: "100%",
      padding: "12px",
      backgroundColor: "black",
      color: "white",
      border: "none",
      borderRadius: "10px",
      fontSize: "16px",
      cursor: "pointer",
      margin: "20px auto",
    },
    link: {
      color: "blue",
      cursor: "pointer",
    },
    label: {
        display: "block",
        textAlign: "left",
        marginTop: "10px",
        fontWeight: "bold",
        fontSize: "14px",
    },
    orText: {
      margin: "0 10px",
      fontWeight: "bold",
      fontSize: "14px",
      color: "black",
    },
    googleButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#fff",
      color: "#000",
      border: "1px solid #ccc",
      borderRadius: "6px",
      padding: "10px",
      width: "100%",
      fontSize: "20px",
      cursor: "pointer",
      marginTop: "10px",
    },
    googleIcon: {
      width: "20px",
      height: "20px",
      marginRight: "10px",
      objectFit: "contain",
    },
  };
export default styles;